# Generated by Django 3.1.4 on 2020-12-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('img_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=350)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('link', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrss.article')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrss.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='subscriptions',
            field=models.ManyToManyField(through='myrss.SubscriptionArticle', to='myrss.Subscription'),
        ),
    ]
