# Generated by Django 3.1.4 on 2020-12-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
