# Generated by Django 3.1.4 on 2020-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='clarin', max_length=300),
            preserve_default=False,
        ),
    ]
