# Generated by Django 3.1.4 on 2020-12-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('img_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('subscriptions', models.ManyToManyField(to='myrss.Subscription')),
            ],
        ),
    ]
