# Generated by Django 3.1.4 on 2020-12-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subscription',
        ),
        migrations.AddField(
            model_name='article',
            name='subscriptions',
            field=models.ManyToManyField(to='myrss.Subscription'),
        ),
    ]
