# Generated by Django 3.1.4 on 2021-01-06 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myrss', '0002_article_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrss.folder')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myrss.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='subscriptions',
            field=models.ManyToManyField(through='myrss.FolderSubscription', to='myrss.Subscription'),
        ),
    ]
