# Generated by Django 3.1.4 on 2020-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0003_auto_20201217_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
