# Generated by Django 3.1.4 on 2021-01-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0003_auto_20210106_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
