# Generated by Django 3.1.4 on 2020-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0004_auto_20201217_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
