# Generated by Django 3.1.4 on 2021-01-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrss', '0005_auto_20210108_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionarticle',
            unique_together={('article', 'subscription')},
        ),
    ]
